[DEFAULT]
logdir = logs
datadir = datadir
importdir = import
tmpdir = tmp
file_format = tiff
collections = Louhans,Seille,Bressans,Autres
collections_map = Louhans,Seille
max_workers = 5

[tkmanager]
images_dir = size_div1
gallery_images_dir = size_div3
last_id = 37
last_filter =

[tkscan]
scanner = escl:https://192.168.1.28:443
resolution = 600
destination = import
prefix = scanned
batch_interval = 20
language = fr
scan_area_enabled = false
scan_area_left = 0
scan_area_top = 0
scan_area_width = 148
scan_area_height = 105
crop_border = 120
jpeg_quality = 85
png_compress = 6
tiff_compression = deflate

[flask]
host = 0.0.0.0
port = 8001
debug = True
secret_key = secret
osm_map = 11/46.6339/5.2096
icon = CPA Louhans

